### ISSUE TITLE
Implement noex::TableAdmin::AsyncCheckConsistency.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1256]
This is **not** a simple async unary RPC.  This is a polling API.

The asynchronous implementation should use the completion queue to poll the long running operation underlying a `CheckConsistency` call.  To wait between polling requests the function should use asynchronous timers in the completion queue.

The first step is to propose the API in the bug, once approved, you must:

- [ ] Implement this new function.
- [ ] Implement an integration test for this new function.

**Comment by dopiera** [comment]
I'm thinking of not exposing `GenerateConsistencyToken` and utilizing it internally in `AwaitConsistency`. The only case where it would be useful to expose it, which came to my mind is waiting for mutations written earlier than the application started. I don't think it's a very useful feature, though.

Due to that, I think the API should be this:
std::shared_ptr<AyncOperation> AwaitConsistency(string const& table_id, string const& consistency_token, CompletionQueue &cq, Functor &&f);

Functor should be invocable with `(CompletionQueue &cq, grpc::Status&)`. `status.ok()` would mean that all mutations written before calling `AwaitConsistency` have made it to their replicas.

Polling and retry policies from the `TableAdmin` object would be used for retrying `GenerateConsistencyToken` or polling `CheckConsistency`.
