### ISSUE TITLE
Uniform treatment find_package(GTest) with vcpkg and non-vcpkg

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1300]
When googletest + googlemock are compiled (and installed) from source they create `GTest::gtest`, `GTest::gtest_main`, `GTest::gmock`, and `GTest::gmock_main` targets.

`find_package(GTest)` creates `GTest::GTest` and `GTest::Main` targets, and nothing for googlemock.

We use some hacks to create the googlemock targets after loading `find_package()`.  We (I really) wrote different hacks when using `vcpkg` vs. when not.  I think the hacks should be the same regardless of how `find_package()` was made to work.

**Comment by ras0219-msft** [comment]
Ah, that would be the difference between the CMakeLists.txt for gtest and CMake's built-in FindGTest[1] (nothing _directly_ caused by vcpkg unfortunately :( so it's not easy to fix).

We could look at better supporting the gtest from-source targets, which should be findable with `find_package(GTest CONFIG REQUIRED)`, though I really don't like having two ways to do something :)

[1] https://cmake.org/cmake/help/latest/module/FindGTest.html
