### ISSUE TITLE
Make StatusOr<T>::value()&& return by value.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1790]
Having `StatusOr<T>::value()&&` return by ref-ref produces surprising results in code like this:

```C++
// Assume ListFoo() returns StatusOr<vector<Foo>>
for (auto const& v : ListFoo().value()) {
}
```

The problem is that the life of the temporary returned by `ListFoo()` is extended until the end of the expression, but not until the end of the statement, so the reference returned by `.value()` becomes invalid.

**Comment by coryan** [comment]
@devjgm any thoughts on this?  I ran into this problem when making other changes and pushed the decision about `.value()` until later.

**Comment by devjgm** [comment]
Yea, I know about this issue. Sadly, I don't know of a great solution in general. Yes, changing value() to return by-value will fix the dangling ref problem as you suggested. But the downsides of that are:

* It's slightly less efficient (more moves/copies than are necessary)
* It doesn't match the behavior of `std::optional::value()` and the proposed signatures for `std::expected::value()`, though admittedly the latter could still be changed.

And due to con 2 above, I suspect that `absl::StatusOr` will keep its current behavior which matches std::optional and returns ref-ref.

Also, the above problem could be considered a bug in the specification for range-for. See http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_closed.html#900. So, it looks like the committee is reasonably considering fixing the spec so that the range-for would correctly extend the lifetime of the temporary returned from ListFoo(). Of course, I doubt the fix would be backported to earlier language standards/compilers, so we couldn't really rely on it.

Due to the similarities, using std::optional would also exhibit the same bugs. So it may be reasonable and not too difficult to implement and upstream a clang-tidy check that warns on buggy uses of std::optional, absl::StatusOr (once it arrives), and even std::expected (if it has the same issue). 

Q: How often did this show up? I imagine it should rarely if ever show up in our actual library code, because we'd probably always forward along the whole StatusOr, or else check the validity of it before dereferencing. I suspect this is also the common pattern when using std::optional: Check the validity, then use the contained value.

If this mostly/only shows up in our sample code, maybe we want to write the sample code to check the validity then dereference?

**Comment by coryan** [comment]
> Q: How often did this show up?

When I was writing the example for `ListObjects()`, I fixed it, but my first implementation was busted.

> If this mostly/only shows up in our sample code, maybe we want to write the sample code to check the validity then dereference?

That is what we are doing.

As a developer used to exceptions I would write my code by calling `.value()`, and this was super surprising, I expect we will get bug reports about this. Closing for now so we can reference it, because the consistency with `std::optional` and `std::expected` seems desirable.
