### ISSUE TITLE
Write down design doc for Row Range and Row Set wrappers

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#31]
Write down a design document for row ranges and row sets.  Document the implementation steps as issues in this repository.

**Comment by achakrab** [comment]
RowRange:
The implementation for this class is straightforward: denote  the range with two keys -- start and limit.  Infinite ranges are indicated with limit="" (that means, we can't have empty  RowRange with start="", which requires a separate wrapper for keys, like RowKey). 
 

We  will provide a private method   SuccessorKey that, given a key k, will  return the key that immediately follows k in the key space (or its domain).

Using this method, we can emulate the  following ranges by converting them to canonical ranges ( assumption:  a left closed, right open range is a canonical one for BigTable server-side  code, as with C++  STL) : 
1. right_open, i.e,,  left closed, right open [begin, end) : default [start, limit), start=begin, limit = end;
2. closed_interval [begin, end], i.e.,  left closed, right closed: final range is [start, limit), where start=begin, limit= SuccessorKey(end)
3. left_open, i.e.,  left open, right closed (start, end]: final range is [start, limit), where start=SuccessorKey(begin), limit=SuccessorKey(end)
4. prefix_range(prefix): final rang is  [start, limit), where  start = prefix, limit = SuccessorKey(prefix)


RowSet Wrapper: 
We need to use a library module  IntervalMap, which is also used by the server side code. This IntervalMap would store the set of ranges, providing various methods for membership check (e.g., check if a single row exists in the set, or range of rows overlaps or lies completely within the RowSet).
Methods to be supported:
1. AddRow :   add an interval  [k, SuccessorKey(k)) for the row with key k; and don't care if the row already exists in the interval tree; such anomalies are dealt with the underlying logic of the interval tree, and this is  the norm also for the  server-side code (in java or C++).
2. AddRange: add the interval using the 'set'  API for the interval tree.


Comments: 
2. Is the interval tree or RowSet passed (as a proto message) to the server side?  If yes, would the server side code access or manipulate  the data structure using  RowKey instead of underlying 'string' type?  
Looks like it might not; the server side might use RowKey just to populate the RowSet; and once the  initialization of the row set is done, the data structure is passed to the executor which relies on the underlying data type in the RowSet and it's interval map (i.e., the executor takes the key types directly from the proto buffer representing the RowSet).

**Comment by coryan** [comment]
I think the bug did not describe the problem well, let me give it a shot.  We want users to be able to say things like this:

```C++
auto results = table->ReadRows(bt::RowSet(
    "foo", "bar", bt::RowRange::left_open("a", "c"), bt::RowRange::right_open("f", l")));
```

that is, mix ranges (of different kinds), and single rows into a virtual collection.  Those collections need to be mapped into the underlying `google::bigtable::v2::RowSet` protobuf.

Here is a propose list of operations to create `RowRanges`:

```C++
class RowRange {
public:
  //  unspecified stuff here, but basically ways to get to the beginning and end.
  // Create different types of ranges:
  static RowRange infinite_range();
  // an empty range
  Static RowRange empty();
  // the typical C++ range [begin,end)
  static RowRange right_open(std::string begin, std::string end);
  // a open interval (begin, end)
  static RowRange open_interval(std::string begin, std::string end);
  // a closed interval [begin, end]
  static RowRange closed_interval(std::string begin, std::string end);
  // a half-open interval (begin, end]
  static RowRange left_open(std::string begin, std::string end);
  // all the rows starting with @a prefix
  static RowRange prefix_range(std::string prefix);
  // an alias for right_open()
  static RowRange range(std::string begin, std::string end);
  // Some accessors
  bool contains(absl::string_view string) const;
  bool operator==(RowRange const&) const;
  bool operator!=(RowRange const& rhs) const { return !(*this == rhs); }
  // TODO(coryan) - maybe other operators, remember std::rel_ops<>
  // the intersection of two ranges (useful for retries)
  static RowRange intersect(RowRange const& lhs, RowRange const& rhs);
};
std::ostream& operator<<(std::ostream&, RowRange const&);```

```proto
class RowSet { public:
  template<typename... Args>
  RowSet(Args&&... k) {
    // call Add() for each "k" in the parameter pack
  }

  // And a key or range
  RowSet& Add(std::string rowkey);
  RowSet& Add(absl::string_view rowkey);
  RowSet& Add(RowRange range);
};
```
The questions to figure out are:

* How is that constructor with the parameter pack implemented (it should not be hard in C++17, but we are sticking to C++11)
* How does this map into the protobuf?  Is there a `Export()` member function that takes the protobuf as an in/out argument?  Does it return a protobuf?  Or a `MoveTo()` member function that destructively moves into the protobuf parameter?

**Comment by achakrab** [comment]
1. That initialization looks interesting. Can we use a constructor with initialize_list (which would basically reuse the AddRow() or AddRange() methods)?  
2. I think mapping the RowSet to protobuf falls on the part of ReadRows rpc call; this method would translate the input parameter RowSet to a format compatible with the server side. That means out RowSet should be polymorphic to the respective parameter type for ReadRows. Any thoughts?

**Comment by coryan** [comment]
1. I assume you mean the initialization from the variadic args?  Using a `std::initialize_list<T>` requires homogenous types.  You could make that work with something like:
```C++
Blah key(std::string const& key);
Blah infinite_range(...);
Blah right_open(...);

class RowSet { public:
  RowSet(std::initialize_list<Blah> list);
};
```

Notice that the accessors for `std::initializer_list<T>` only get you `T const&` (in the lingo `std::initializer_list<T>::reference` is a `T const&`.  That means you have to copy the objects out of the initializer list, you cannot do move copy for them, whereas you can avoid the copies in the variadic templates.  That is a minor issue in this case, but full disclosure and all that.

2. For that to work the `Table::ReadRows` member function would need either (a) enough accessors to the `RowSet` data to figure out the keys and ranges that are stored inside it, or (b) be a friend so it can access the internals.  I do not like option (b), too much coupling.  Option (a) is viable, but requires substantially more accessors for a class (`RowSet`) that is essentially a builder to create the proto.  Why not make `RowSet` responsible for creating / populating the proto and call it a day?

**Comment by achakrab** [comment]
1. You are right, initializer_list will not work. variadic templates would work fine. 
2.  That means, ReadRows will take a proto as the input parameter (that corresponds to RowSet)?  
So, we need a proto for  row set  which would be wrapped inside the RowSet class, as done in Go: 
```
type RowSet interface {
	proto() *btpb.RowSet

	// retainRowsAfter returns a new RowSet that does not include the
	// given row key or any row key lexicographically less than it.
	retainRowsAfter(lastRowKey string) RowSet

	// Valid reports whether this set can cover at least one row.
	valid() bool
}
```

**Comment by achakrab** [comment]
Also, can we have an overloaded method Add(string), Add(RowRange) within RowSet in place of AddRow(string), AddRange(RowRange)? That would make the RowSet constructor with variadic template simple.

**Comment by coryan** [comment]
Yes, having an overloaded member function is perfectly fine.  Consider making those private and a non-overloaded version in the public interface to keep the interface less confusing for folks.  That is a weak suggestion, I am generally fine with overloads, but the style guide suggests that might not be always good.

**Comment by achakrab** [comment]
As for RowSet class, I am thinking of this structure:
```
class RowSet {
 public:
  RowSet(RowSet&& rhs) noexcept = default;
  RowSet& operator=(RowSet&& rhs) noexcept = default;
  RowSet(RowSet const& rhs) = default;
  RowSet& operator=(RowSet const& rhs) = default;
  RowSet() = default;

  template <typename First, typename... Rest>
  RowSet(First&& argFirst, Rest&&... argRest);
  
  RowSet& Add(std::string rowKey);
  RowSet& Add(absl::string_view rowKey);
  RowSet& Add(RowRange rowRange);

  // Return the RowSet expression as a protobuf.
    google::bigtable::v2::RowSet as_proto() const { return row_set_; }

 private:
  google::bigtable::v2::RowSet row_set_;
};

```
Am I missing any other methods? 
Should I define the methods in the header file (like Filters.h)? Or, Can I define the methods in row_set.cc?
