### ISSUE TITLE
Remove class collaboration diagrams from user-facing docs

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#322]
These are no useful to user, and their usefulness to developers is even doubtful.  For an example:

https://coryan.github.io/google-cloud-cpp/classRowReaderTest.html

**Comment by manish-qlogic** [comment]
```
set(DOXYGEN_COLLABORATION_GRAPH NO)
set(DOXYGEN_INCLUDE_GRAPH NO)
```
i am checking if above two variables can remove collaboration diagram and include graph in html. I tried this with docker image of fedora with GENERATE_DOCS=yes.
But classRowReaderTest.html  is not generated at all.

or is it due to the fact that testing is in exclude pattern, 
`set(DOXYGEN_EXCLUDE_PATTERNS "*/client/internal/*;*/client/testing/*;*/*_test.cc")`

**Comment by manish-qlogic** [comment]
Need to set following in DocxygenCommon.cmake 

```
set(DOXYGEN_CLASS_GRAPH NO)
set(DOXYGEN_COLLABORATION_GRAPH NO)
set(DOXYGEN_INCLUDE_GRAPH NO)
set(DOXYGEN_INCLUDED_BY_GRAPH NO)

```
Please see for further reference:-
https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_class_graph

I will raise a PR with the fix.

**Comment by manish-qlogic** [comment]
#397 also fixes this issue, is there anything else to be done here?

**Comment by coryan** [comment]
Indeed, #397 also fixed this, I just did not use the magic words in the commit message.
