### ISSUE TITLE
Implement additional Credential features

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#579]
We need to create a design document describing all the features needed with respect to credentials and authentication, including "no authentication", "use gce metadata for authentication", "use hmac", "oauth on behalf of a user".  Then we need to implement all those features.

**Comment by coryan** [comment]
Also, we should think about API keys.

**Comment by houglum** [comment]
I've been working on refactoring our OAuth2 credential functionality, so I'll add an update to this issue. No-auth and user-auth are already implemented; automatic GCE service account credentials (i.e. without supplying the path to a JSON keyfile) still need to be implemented.

Open questions on remaining credential types and whether we should support them:
- Service account credentials loaded from a P12 keyfile
- HMAC credentials

**Comment by coryan** [comment]
Can we declare success and close this issue?  And if there is some amount of work still left to do: create a small issue describing exactly that work?

**Comment by houglum** [comment]
Yeah, I think we're okay to call this done.  The only things I can think of that are left aren't really needed (and we can implement them later when/if they are):

-  Verify GAEF support (from what I've read, this should just work using the GCE creds... but nobody is asking for this, since you'd have to build a custom GAEF runtime).
-  Support 2FA flow for authorized user credentials (I don't think any of the other client libraries handle this; this is one of the many reasons we strongly encourage users to use service account credentials instead -- @frankyn please correct me if I'm wrong).
-  Add a non-refreshing credential type (e.g. just passing an access token / authorization header value directly -- mostly used for debugging purposes, or if you know your program won't take an hour to finish, and thus won't need to refresh the credential).

**Comment by frankyn** [comment]
According to the following doc you can perform 2FA flow with Python libraries, not sure about all libraries, but I suspect yes.
https://cloud.google.com/docs/authentication/end-user#end_user_authentication_example

cc: @theacodes who will know this space better. Thea is it an expectation for client libraries to support the 2FA flow credential flow?

**Comment by theacodes** [comment]
For Cloud, 2FA is not high priority because we recommend people use service accounts in production.

**Comment by frankyn** [comment]
Thanks Thea!

@houglum other libraries do support this feature but isn't a high priority. Should we leave this comment open?

**Comment by houglum** [comment]
Let's create a child issue and mark this (more general-purpose one) as closed.
