### ISSUE TITLE
Troubleshoot flaky polling_policy_test

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#713]
The policy test is failing from time to time:

```
44/60 Test #44: polling_policy_test .........................................***Failed    0.41 sec
Running main() from gtest_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from GenericPollingPolicy
[ RUN      ] GenericPollingPolicy.Simple
/v/google/cloud/bigtable/polling_policy_test.cc:59: Failure
Value of: actual
  Actual: false
Expected: true
```

**Comment by coryan** [comment]
cc: @hemant-qlogic can you take a look?

**Comment by hemant-qlogic** [comment]
How to simulate this case.
I tried with following values
1.
    kLimitedTimeTestPeriod = 50ms 
    kLimitedTimeTolerance = 10ms
  100 times executed the polling_policy_test over production, but did not failed.
2.
    kLimitedTimeTestPeriod = 50ms 
    kLimitedTimeTolerance = 1ms
  100 times executed the polling_policy_test over production, but did not failed.
3.
    kLimitedTimeTestPeriod = 50ms 
    kLimitedTimeTolerance = 0ms
  100 times executed the polling_policy_test over production, 
  then it failed with above error message some times.

  how to simulate this case.

**Comment by coryan** [comment]
I assume the expectations that fail are these:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/7228b50dc12fa8a42b82773d2773301008e81b2b/google/cloud/bigtable/polling_policy_test.cc#L59

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/7228b50dc12fa8a42b82773d2773301008e81b2b/google/cloud/bigtable/polling_policy_test.cc#L61

If I am wrong, please ignore me.

The first thing I would do is add some logging to the expectations, something like:

```
auto elapsed_ms = std::chrono::duration_cast<milliseconds>(now - start).count();
EXPECT_TRUE(actual) << "In iteration " << i << " after " << elapsed_ms << "ms";
```

That way when it happens in the CI build again we will have more information.


Second, let's be more generous with the timeouts, set `kLimitedTimeTestPeriod = 100ms` and `kLimitedTimeTolerance` to 20ms.  Remember to change the comments.

I would also change the sleep time to 5ms.  And finally, we can exit that loop after the first successful `EXPECT_FALSE()`.

I am guessing that the CI machines are a lot more loaded than your workstation, you can try to run the test while at the same time creating load (building the code or running `dd` should do it).  You can also manually run the test with `--gtest_repeat=1000` to repeatedly run the test until it fails.

**Comment by hemant-qlogic** [comment]
I tried to investigate the issue and found that
there is only one condition where the test case will fail.

Following are the two sequential lines in the 
function "CheckLimitedTime" in polling_policy_test.cc
which are responsible for the test case fail
------------------------------
auto actual = tested.OnFailure(grpc::Status(grpc::StatusCode::UNAVAILABLE, "please try again"));
auto now = std::chrono::system_clock::now();
------------------------------
Due to server overload if there is a delay of more 
than double the value of "kLimitedTimeTolerance" milliseconds
between these two statements then the test case will fail. 

The solutions I can think of is as follows.
The problem is due to time received at different timestamp 

So Can we change the logic to get the timestamp from one place.
i.
1. Generate timestamp in the "CheckLimitedTime" and pass it to 
   GenericPollingPolicy::OnFailure and use it in "LimitedTimeRetryPolicy::on_failure" 
   to return the value for "actual".
   Same timestamp should be used in checking the case failure.
2. Generate timestamp inside "LimitedTimeRetryPolicy" and use it in
   "LimitedTimeRetryPolicy::on_failure" and get it with "GenericPollingPolicy"
   inside "CheckLimitedTime" for handling the test validity.

I think this way we can avoid the test failure due to server overload.
Can I try these solutions.  if yes Which one is preferred solution?

**Comment by coryan** [comment]
What do you think of this.  Change this code:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/7228b50dc12fa8a42b82773d2773301008e81b2b/google/cloud/bigtable/polling_policy_test.cc#L54

To look like this:

```C++
int true_counter = 0;
int false_counter = 0;
for (int i = 0; i != 100; ++i) {
    auto start = std::chrono::system_clock::now();
    auto actual = tested.OnFailure(
        grpc::Status(grpc::StatusCode::UNAVAILABLE, "please try again"));
    auto now = std::chrono::system_clock::now();
    if (start < must_be_true_before and now < must_be_true_before) {
      // The function spent all the time in the interval where the result must be true,
      // check that indeed it returned true.
      EXPECT_TRUE(actual);
      ++true_counter;
    } else if (must_be_false_after < start and must_be_false_after < now) {
      // The function spent all the time in the interval where the result must be false,
      // check that indeed it returned false.
      EXPECT_FALSE(actual);
      ++false_counter;
    }
    // in other cases the result is indeterminate, so do not have any expectations about it.
    std::this_thread::sleep_for(1_ms);
  }
  EXPECT_LE(0, true_counter);
  EXPECT_GE(0, false_counter);
```

I guess we could also change the policies to use a mockable clock, but that would require a lot of changes.

**Comment by coryan** [comment]
Also, there is a similar function in another test, which maybe just because we are lucky (or the surrounding tests produce less load) is passing.  Whatever approach we adopt, can you fix the other function too:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/40bc01bc953c940d899b755fd924341b86e2df73/google/cloud/bigtable/rpc_retry_policy_test.cc#L42
